name: dart_code_metrics_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 5.7.5
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dart_code_metrics:
    git:
      url: https://github.com/JonasWanke/dart-code-metrics.git
      ref: b2109f55f829528df450f01b3b84aa3d0b8add25

dev_dependencies:
  lints: ^1.0.1
